version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
<<<<<<< HEAD
s3_bucket = "todo-list-aws-default"#"aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
=======
s3_bucket ="todo-list-aws"
>>>>>>> 04d972115aaaede5a5abf1faaaebfb4935e91f1a
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
#resolve_s3 = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
<<<<<<< HEAD
s3_bucket = "todo-list-aws-staging"#"aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
=======
s3_bucket = "todo-list-aws-staging"
>>>>>>> 04d972115aaaede5a5abf1faaaebfb4935e91f1a
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
<<<<<<< HEAD
s3_bucket = "todo-list-aws-production"#"aws-sam-cli-managed-production-samclisourcebucket-upt09go84tay"
=======
s3_bucket =  "todo-list-aws-production"
>>>>>>> 04d972115aaaede5a5abf1faaaebfb4935e91f1a
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
